name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup code repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: printing directory
        run: ls -la
      - name: install dependencies
        working-directory: ./frontend
        run: npm ci
      # - run: npm test
